# Generated by Django 4.0.3 on 2022-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_ingredients_ing_mod_date_ingredients_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
