# Generated by Django 4.0.3 on 2022-03-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_ingredients_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
