# Generated by Django 4.0.3 on 2022-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_supplier_phonenumber_supplier_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ing_mod_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
