# Generated by Django 4.0.3 on 2022-03-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brandname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('Piece', 'Pieces'), ('Kilogram', 'Kilograms'), ('Litre', 'Litre'), ('Box', 'Box'), ('1 Kg Bag', '1 Kg Bag'), ('15 Kg Bag', '15 Kg Bag'), ('20 Kg Bag', '20 Kg Bag'), ('1 Lt Bottle', '1 Lt Bottle'), ('4 Lt Bottle', '4 Lt Bottle'), ('5 Lt Bottle', '5 Lt Bottle'), ('4 Lt Bucket', '4 Lt Bucket'), ('20 Lt Bucket', '20 Lt Bucket')], max_length=20, null=True),
        ),
    ]
