# Generated by Django 4.0.3 on 2022-03-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_ingredient_brand_alter_brand_brandname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=5)),
                ('main_unit', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
